import { HomePage } from '@/views/home-view'
import { NextPageWithLayout } from '@/shared/@types'
import Head from 'next/head'

export interface Info {
  count: number
  pages: number
  next: string
  prev: any
}
export interface Result {
  id: number
  name: string
  status: string
  species: string
  type: string
  gender: string
  origin: object
  location: object
  image: string
  episode: any[]
  url: string
  created: string
}
export interface Character {
  info: Info
  results: Result[]
}

const Home: NextPageWithLayout = () => (
  <div>
    <Head>
      <>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </>
    </Head>
    <HomePage />
  </div>
)

export default Home
