import Head from 'next/head'
import { HomePage } from '@/views/home-view'
import { NextPageWithLayout } from '@/shared/@types'

const Home: NextPageWithLayout = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
    </Head>
    <HomePage />
  </div>
)

export default Home
